### PR TITLE
Update: Quarkus -> 2.2.0, Kotest -> 5.0-SNAP

### PR DESCRIPTION
**Pull request by GavinRay97**
It still fails, but now it's up to date and failing 😅

### CODE REVIEW

**Comment by snowe2010** [comment]
3 spaces?

**Comment by sksamuel** [comment]
Like a real repo :)

**Comment by GavinRay97** [comment]
LMAO I have no idea how that happened. 🙈 
I only use IntelliJ for JVM code, and I guess this shows it hahaha

**Comment by sksamuel** [comment]
It's because I have it set via .editorconfig and intellij respects it.

**Comment by GavinRay97** [comment]
The absolute madlad -- so you do!

image

**Comment by sksamuel** [comment]
I had 2 originally, as I was a Scala guy for so long.
But people thought 2 was too weird.... and I hate 4 so....

**Comment by snowe2010** [comment]
hm. Weird that IntelliJ didn't respect that when I added all the example code though.

**Pull request merged**
